name: apiverve_asnlookup
description: ASN Lookup is a simple tool for getting information on Autonomous System Numbers (ASNs). It returns information on various ASNs.
version: 1.1.13
homepage: https://apiverve.com/marketplace/asnlookup?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/asnlookup-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
